DROP TABLE IF EXISTS ALBUM_CONTRIBUTOR CASCADE;
DROP TABLE IF EXISTS ALBUM_INFO CASCADE;
DROP TABLE IF EXISTS ALBUM CASCADE;
DROP TABLE IF EXISTS ARTIST CASCADE;

CREATE TABLE ARTIST (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    country TEXT
);

CREATE TABLE ALBUM (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    release_year SMALLINT NOT NULL CHECK(release_year >= 1900 AND release_year <= EXTRACT(YEAR FROM CURRENT_DATE)),
    primary_artist_id INT REFERENCES ARTIST(id) ON DELETE RESTRICT NOT NULL
);

CREATE TABLE ALBUM_INFO (
    album_id INT PRIMARY KEY REFERENCES ALBUM(id) ON DELETE CASCADE,
    upc CHAR(12) UNIQUE NOT NULL,
    label TEXT,
    duration_minutes SMALLINT NOT NULL CHECK(duration_minutes > 0)
);

CREATE TABLE ALBUM_CONTRIBUTOR (
    album_id INT REFERENCES ALBUM(id) ON DELETE CASCADE,
    artist_id INT REFERENCES ARTIST(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    PRIMARY KEY(album_id, artist_id, role)
);